name: Release
on:
  release:
    types:
      - published
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: ansible-galaxy role import
        run: |
          ansible-galaxy role import --token "$ANSIBLE_TOKEN" --role-name mackerel-agent mackerelio ansible-mackerel-agent
        env:
          ANSIBLE_TOKEN: ${{ secrets.ANSIBLE_TOKEN }}
